# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
# 
# background on yaml build pipelines versus classic: https://www.reddit.com/r/azuredevops/comments/166el30/stop_dont_use_azure_devops_release_pipelines/


trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build
    displayName: Build Stage
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        
#    - task: DotNetCoreCLI@2
#      inputs:
#        command: publish
#        publishWebProjects: True 
#        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
#        zipAfterPublish: True 
    - task: DotNetCoreCLI@2 #https://learn.microsoft.com/en-us/training/modules/create-release-pipeline/5-deploy-to-appservice
      inputs:
        command: publish
        projects: '**/*.csproj' #instead, probably should set to only the webapp project
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: True 

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy_to_Test
  displayName: Deploy to Test Stage
  jobs:
  - job: Deploy
    displayName: Deploy Stage
    steps:
    - download: current
      artifact: drop
    #- task: DownloadBuildArtifacts@0
    #  inputs:
    #    buildType: 'current'
    #    downloadType: 'single'
    #    artifactName: 'drop'
    #    downloadPath: '$(System.ArtifactsDirectory)'    
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Azure subscription 1(5b2d29c4-2e1c-4bfc-9da0-f0226643249b)'
        appType: 'webApp'
        appName: 'PigLatinTesting'
        #package: '$(System.ArtifactsDirectory)/**/*.zip'
        package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'
        #deploymentMethod: 'auto'
        